package io.thundra.merloc.aws.lambda.runtime.embedded;

/**
 * @author serkan
 */
public interface LambdaEnvironmentVariables {

    String HANDLER_ENV_VAR_NAME = "_HANDLER";
    String AWS_TRACE_ID_ENV_VAR_NAME = "_X_AMZN_TRACE_ID";
    String AWS_REGION_ENV_VAR_NAME = "AWS_REGION";
    String AWS_LAMBDA_FUNCTION_INVOKED_ARN_ENV_VAR_NAME = "AWS_LAMBDA_FUNCTION_INVOKED_ARN";
    String AWS_LAMBDA_FUNCTION_NAME_ENV_VAR_NAME = "AWS_LAMBDA_FUNCTION_NAME";
    String AWS_LAMBDA_FUNCTION_MEMORY_SIZE_ENV_VAR_NAME = "AWS_LAMBDA_FUNCTION_MEMORY_SIZE";
    String AWS_LAMBDA_FUNCTION_VERSION_ENV_VAR_NAME = "AWS_LAMBDA_FUNCTION_VERSION";
    String AWS_LAMBDA_LOG_GROUP_NAME_ENV_VAR_NAME = "AWS_LAMBDA_LOG_GROUP_NAME";
    String AWS_LAMBDA_LOG_STREAM_NAME_ENV_VAR_NAME = "AWS_LAMBDA_LOG_STREAM_NAME";
    String AWS_LAMBDA_INITIALIZATION_TYPE_ENV_VAR_NAME = "AWS_LAMBDA_INITIALIZATION_TYPE";
    String AWS_EXECUTION_ENV_ENV_VAR_NAME = "AWS_EXECUTION_ENV";

}
